# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
Import torch


# Create random tensor
x = torch.rand(7, 7)

print(x)
print(x.shape)

tensor([[0.5002, 0.4485, 0.2538, 0.5113, 0.7090, 0.1939, 0.7437],
        [0.8705, 0.9428, 0.4113, 0.9434, 0.5915, 0.1998, 0.5545],
        [0.7241, 0.9913, 0.0162, 0.1358, 0.0270, 0.3270, 0.3335],
        [0.4443, 0.2271, 0.7714, 0.8746, 0.0611, 0.8166, 0.3891],
        [0.9721, 0.7848, 0.2582, 0.8108, 0.8667, 0.1764, 0.6584],
        [0.4188, 0.1784, 0.5082, 0.1568, 0.6004, 0.4088, 0.2214],
        [0.1347, 0.1522, 0.3788, 0.6869, 0.3595, 0.7167, 0.0345]])
torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
y = torch.rand(1,7)
y
# Perform matrix multiplication
Z = torch.matmul(x, y.T)
Z, Z.shape

(tensor([[2.2100],
         [3.1475],
         [2.0252],
         [2.2902],
         [3.0619],
         [1.5308],
         [1.2647]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(7,7)
y = torch.rand(1,7)

# Matrix multiply tensors
z = torch.matmul(x, y.T)
z, z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [13]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [4]:
import torch

# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(2,3).to(device)
tensor_B = torch.rand(2,3).to(device)
tensor_A, tensor_B

Device: cpu


(tensor([[0.5001, 0.2539, 0.8345],
         [0.9108, 0.4923, 0.3329]]),
 tensor([[0.2317, 0.8258, 0.9592],
         [0.4744, 0.1310, 0.5267]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [3]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.9188, 0.6548],
         [1.0721, 0.7522]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [10]:
# Find max
max = torch.max(tensor_C)
max
# Find min
min = torch.min(tensor_C)

print(f"Max: {max}, Min: {min}")

Max: 1.072096347808838, Min: 0.654790461063385


### 9. Find the maximum and minimum index values of the output of 7.

In [12]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)

arg_max, arg_min

(tensor(2), tensor(1))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [14]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors and their shapes

print(f"tensor_D: {tensor_D}, shape: {tensor_D.shape}")
print(f"tensor_E: {tensor_E}, shape: {tensor_E.shape}")

tensor_D: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), shape: torch.Size([1, 1, 1, 10])
tensor_E: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), shape: torch.Size([10])
